APP_TITLE = "采购单智能分析"
PAGE_ICON = "📊"
LAYOUT = "wide"

DEFAULT_DELIVERY_CYCLE_DAYS = 5
DEFAULT_REPLENISHMENT_CYCLE_DAYS = 7
DEFAULT_PRICE_ALERT_THRESHOLD = 5.0
LARGE_ORDER_AMOUNT = 100000

ALERT_RED = "🔴 红色（紧急）"
ALERT_ORANGE = "🟠 橙色（重点跟进）"
ALERT_YELLOW = "🟡 黄色（常规提醒）"

FULFILLMENT_FULL = "足额满足"
FULFILLMENT_PARTIAL = "部分满足"
FULFILLMENT_NONE = "未履约"

STATUS_COMPLETED = "已完成"

TIMELINESS_NORMAL = "正常履约"
TIMELINESS_MINOR = "轻微逾期"
TIMELINESS_SEVERE = "严重逾期"
